### ISSUE TITLE
YoloV5 C# detection is less accurate

### ISSUE THREAD

**Issue by afisk** [BobLd/YOLOv4MLNet#10]
I am finding that the object detection is different and maybe less accurate in C# with the onnx model than it was in Python with the PyTorch model. Is there any fix or reason for this?
I have resized my images to be 640x640 to hopefully avoid any differences in image resizing.  I also have the same confidence and IOU thresholds in both and get different results.  

C#: 
![623 _pro](https://user-images.githubusercontent.com/31937676/121415928-da69a500-c92d-11eb-85cf-d2f775396c32.png)
Python: 
![623](https://user-images.githubusercontent.com/31937676/121415941-dfc6ef80-c92d-11eb-8509-6d2379413fb0.jpg)

C#: 
![656 _pro](https://user-images.githubusercontent.com/31937676/121416791-d2f6cb80-c92e-11eb-90cc-6e9532692b3e.png)
Python:
![656](https://user-images.githubusercontent.com/31937676/121416717-bd81a180-c92e-11eb-831a-294e1d6ea579.jpg)

Any idea why the Python & PyTorch model seems to preform better?

**Comment by BobLd** [comment]
I can't really answer on the PyTorch/onnx difference as I'm no specialist, but I would expect the models to behave similarly... (also depending on how you did the conversion)

Below are stuffs I would invertigate:
- Is the C#/onnx model working for some pictures (in what you've displayed, it's always failing)?
- Are the raw outputs from the models identical (i.e. before post-processing of the outputs)? You will need to understand the Python code and print in some way the outputs before post-processing (here, I assume the outputs have the same shapes for both models...)
- Is post-processing done the same way? An important part of it is done here: https://github.com/BobLd/YOLOv4MLNet/blob/0104728917e3001e5b04feb794c3ffcb6dd8a819/YOLOv4MLNet/DataStructures/YoloV4Prediction.cs#L74-L108 The NMS stands for "non max suppression" and might be done differently in PyTorch... 
- I'd try to display on pictures all the results from the C#/onnx, and try to undestand if the expected candidate bounding box are here.

Hope this helps

**Comment by afisk** [comment]
I turned off the NMS (never let it delete a box) and it appears that it is still not finding the images.. do you think the .pt to onnx converter might be bad? I used the one that came with the ultralytics/yolov5 .

C# NMS at .45 - Finds right side deer
![629 _pro](https://user-images.githubusercontent.com/31937676/121422702-1c4a1980-c935-11eb-91f8-5d085adf418e.png)
C# no NML - finds right side deer
![629 _proc](https://user-images.githubusercontent.com/31937676/121422646-0f2d2a80-c935-11eb-94b0-b2bd473b94e7.png)
Python .45 NMS - finds both deer
![629](https://user-images.githubusercontent.com/31937676/121422581-ff154b00-c934-11eb-846e-1802ed93927d.jpg)

**Comment by BobLd** [comment]
okay that's strange... The scores are still different for the correctly found bounding box (0.88 in C# vs. 0.94 in Python)

- Can you also deactivate the IoU thresold if not already done and check the output? (comment the line below)
https://github.com/BobLd/YOLOv4MLNet/blob/0104728917e3001e5b04feb794c3ffcb6dd8a819/YOLOv4MLNet/DataStructures/YoloV4Prediction.cs#L50
- Really don't know but I'd expect the converter to work fine.
- What about the pre-processing of the image? How do you feed the image to the onnx model? And how is it done in Python? Is there any colour balancing in the Python version...?
- Something else to try if possible would be to use the onnx model direcly from Python... Is ultralytics providing the Python code for the onnx model processing?

**Comment by afisk** [comment]
This is pretty much every image with the threshold turned off:
![621 _proc](https://user-images.githubusercontent.com/31937676/121431211-bbbfda00-c93e-11eb-9d07-9fd76e416f2c.png)

The pre-processing looks okay to me. There should be no resizing since I am feeding in the size of the model's inputs, 640x640. There is scaling: img/255. Python is nice and does most of the hard work and thinking for you :)

I'm not married to YoloV5 so maybe it would be easier to switch to YoloV4. With your YoloV4, how were you creating your onnx files and were all of your objects being found both in the original YoloV4 model and the Onnx?

**Comment by BobLd** [comment]
haha quite messy

- I'd be you I would try to understand what's going on with your current c# code, you seem to be very close. Try uncommenting your `if (objConf <= scoreThres) continue;` on put a low `scoreThres`, to someting like 0.1 and increasing it. You will see less and less bounding boxes and I'd hope to see the second deer... This should help understand...
- On my side I didn't trained my models, I was just reusing already existing onnx models. So I won't really be able to help here.
- As far as I remember, I did train a YoloV3 model and converted it to onnx. Maybe have a look here: https://github.com/BobLd/YOLOv3MLNet I have put the Python code I used for the conversion.

**Comment by afisk** [comment]
Darn.
It starts detecting the second deer once the confidence score gets below 0.0003:
![629 _proc](https://user-images.githubusercontent.com/31937676/121435036-dd6f9000-c943-11eb-9a1b-69a8ddf3541d.png)

I'll go look through that YoloV3 and see if I can find something useful in that too! :)

**Comment by afisk** [comment]
YOU WERE RIGHT! Very close!! :) :) :)
My pytorch model output is 10647x17classes (for 416x416 images    ((52 x 52) + (26 x 26) + 13 x 13)) x 3 = 10647).. the converted model (onnx) has an output size of 25200x17 classes. I converted the pt to onnx converter to take in 416x416 images.  The drawings are a little off, but the confidences are almost on point and the boxes show up in the relative areas of where the objects are in relation to one another. I'll try and get the bounding boxes to show in the correct places tomorrow and update here. Thank you very very much for all of your help (and encouragement) so far!!

C# 416x416:
![629 _proc](https://user-images.githubusercontent.com/31937676/121437548-2590b180-c948-11eb-907c-6225076f8c9a.png)
Python Original Model:
![629](https://user-images.githubusercontent.com/31937676/121437575-304b4680-c948-11eb-9031-e953698910e8.jpg)


C# 416x416:
![656 _proc](https://user-images.githubusercontent.com/31937676/121437710-583aaa00-c948-11eb-8746-09c861cd2860.png)
Python Original Model:
![656](https://user-images.githubusercontent.com/31937676/121437753-61c41200-c948-11eb-98a1-6ec25f110979.jpg)

**Comment by BobLd** [comment]
That's great news! This now seems to be a scaling issue. Just checking but make sure you've updated the following to match your dimensions:
https://github.com/BobLd/YOLOv4MLNet/blob/0104728917e3001e5b04feb794c3ffcb6dd8a819/YOLOv4MLNet/DataStructures/YoloV4Prediction.cs#L31-L32

**Comment by afisk** [comment]
That was it! Works great now!! Thank you sooo much @BobLd !

**Comment by BobLd** [comment]
Great!
