### ISSUE TITLE
Speed To Detect very SLOW

### ISSUE THREAD

**Issue by hohoangan** [BobLd/YOLOv4MLNet#8]
First, Thank you for your source, It has helped me a lot.
But speed to detect the object in an image is slow,
How can faster do it such as use GPU or custom list object, Because I need counting vehicle from the camera.
Please help!

**Comment by orielswisa** [comment]
+1

**Comment by Transigent** [comment]
This has GPU support:
https://github.com/wang-xinyu/tensorrtx
Some benchmarks at the page end.

**Comment by BobLd** [comment]
Hi,

There is already an open issue about that here: https://github.com/dotnet/machinelearning/issues/5597 Unfortunatly, and as explained here, this doesn't come from this code but from the ML.Net/Onnx step.

You can use the GPU. If I remember well you will need to use the following package: https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime.Gpu/
I did some tests in the past and it worked, but you might have error messages that are linked to nuget packages conflicts. You will need to uninstall the cpu package.

**Comment by BobLd** [comment]
Try updating to NL.Net v1.6.0, they have improved image handling and it's much faster.
I've updated the repos with https://github.com/BobLd/YOLOv4MLNet/commit/5cab380bf969a03ed33b9e5569746e844ade4ef7

**Comment by orielswisa** [comment]
> Hi,
> 
> There is already an open issue about that here: [dotnet/machinelearning#5597](https://github.com/dotnet/machinelearning/issues/5597) Unfortunatly, and as explained here, this doesn't come from this code but from the ML.Net/Onnx step.
> 
> You can use the GPU. If I remember well you will need to use the following package: https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime.Gpu/
> I did some tests in the past and it worked, but you might have error messages that are linked to nuget packages conflicts. You will need to uninstall the cpu package.

Hi,

I have nvidia rtx 2080 super i haved try to do that in past but it not work for me,
Are you know which CUDA and cuDNN version i need?

**Comment by BobLd** [comment]
From this recent [article](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-gpu-model-builder), I see that they use
- Install CUDA v10.1
- Install cuDNN v7.6.4 for CUDA 10.1

But I haven't tried yet

**Comment by orielswisa** [comment]
Tnx for your answer!
The Model Builder recognized the GPU but how can it help me with your code?

**Comment by Eclipi** [comment]
I found that the inference speed is a lot faster on .Net Core 5.0. It took around ~8000ms on .NET Framework 4.7.2 and ~600s on Core.
