### ISSUE TITLE
Running YoloV5 Onnx with multiple outputs

### ISSUE THREAD

**Issue by afisk** [BobLd/YOLOv4MLNet#9]
I have a YoloV5 Onnx model with 4 outputs, however I can only use a single output at a time.  If I try reading in all 3 in my YoloV4Prediction.cs class, I get 'Parameter is not valid' when I run predictionEngine.Predict( .. ); in Program.cs. Any ideas on how I can use all 3 output classes at the same time?
{ "output", new[] { 1, 25200, 8 } },
{ "445", new[] { 1, 3, 80, 80, 8 } },
{ "506", new[] { 1, 3, 40, 40, 8 } },
{ "567", new[] { 1, 3, 20, 20, 8 } },

**Comment by BobLd** [comment]
Hi,

Before going any further, can you confirm you had a look at the following:
- https://github.com/BobLd/YOLOv4MLNet/issues/2
- https://gist.github.com/keesschollaart81/83de609f0852670656290fe0180da318
- https://github.com/BobLd/YOLOv4MLNet/tree/yolo-v5-incl
- https://github.com/BobLd/YOLOv4MLNet/tree/yolo-v5

Also, can you make sure your output layers names match the names in the code?

**Comment by afisk** [comment]
@BobLd YOU ARE AMAZING!!!!!!!!!!!!

the https://github.com/BobLd/YOLOv4MLNet/tree/yolo-v5-incl link made this super super easy. I changed a couple things and it worked like a charm!
Thank you Thank you Thank you. I've been looking at this stuff for a couple of days. THANK YOU SOOOOO MUCH!!!!!

**Comment by BobLd** [comment]
My pleasure. Thanks to @raulsf6 too
